name: Flutter Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        run: |
          git clone https://github.com/flutter/flutter.git
          echo "Adding Flutter to PATH"
          echo "$(pwd)/flutter/bin" >> $GITHUB_ENV
          flutter --version
          flutter channel stable
          flutter upgrade
        shell: bash

      - name: Install dependencies
        run: |
          flutter pub get
        shell: bash

      - name: Run Flutter analyzer
        run: flutter analyze
        shell: bash

      - name: Install dart_code_metrics
        run: flutter pub global activate dart_code_metrics
        shell: bash

      - name: Run dart_code_metrics
        run: flutter pub global run dart_code_metrics:metrics
        shell: bash
