name: Flutter Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: 'stable'
          channel: 'stable'
          architecture: 'x64'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter analyzer
        run: flutter analyze

      - name: Install dart_code_metrics
        run: flutter pub global activate dart_code_metrics

      - name: Run dart_code_metrics
        run: flutter pub global run dart_code_metrics:metrics
