name: Dart Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v2
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run Dart analyzer
        run: dart analyze

      - name: Install dart_code_metrics
        run: dart pub global activate dart_code_metrics

      - name: Run dart_code_metrics
        run: dart pub global run dart_code_metrics:metrics
